### ISSUE TITLE
[INFRA] Choose the right testing infrastructure

### ISSUE THREAD

**Issue by bandang0** [bandang0/aamg#4]
Hi,
As discussed in #2 and in [this Setuptools issue](https://github.com/pypa/setuptools/issues/1684), the `python3 setup.py test` command for running all the project's tests will go sunset soon. Since we want to test thouroghly and easily, we should choose a new testing infrastructure.

The people from Setuptools point to the [tox project](https://tox.readthedocs.io/en/latest/). What do you say?

I know nothing on this so I'm open to all suggestions.

**Comment by gabriel-duque** [comment]
Yo!

Tox seems like the proper and generic alternative.

 I have some time now and will look into Tox.

**Comment by bandang0** [comment]
We setup Tox in #8.
